spring:
  #mvc:
    #favicon:
      #enabled: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msg_collect?characterEncoding=UTF-8
    username: root
    password: root
    tomcat-jdbc: com.alibaba.datasource.pool.DruidDataSource
    initialSize: 20                                #初始化连接大小
    minIdle: 5                                     #最小连接池数量
    maxActive: 20                                  #最大连接池数量
    maxWait: 60000                                 #获取连接时最大等待时间，单位毫秒
    timeBetweenEvictionRunsMillis: 60000           #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000             #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM tb_role         #测试连接
    testWhileIdle: true                            #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
    testOnBorrow: false                            #获取连接时执行检测，建议关闭，影响性能
    testOnReturn: false                            #归还连接时执行检测，建议关闭，影响性能
    poolPreparedStatements: false                  #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
    maxPoolPreparedStatementPerConnectionSize: 20  #开启poolPreparedStatements后生效
    filters: stat,wall,log4j         # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防 sql 注入，使用log4j2作为日志框架
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true                   # 合并多个DruidDataSource的监控数据
    # Druid WebStatFilter配置
    web-stat-filter:
      enabled: true
      url-pattern: /*
      exclusions: '*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*'
    # Druid StatViewServlet配置
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
      reset-enable: true
      login-username: admin
      login-password: admin
    # 配置日志输出
    druid:
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
  jpa:
    show-sql: true    #开发时打开sql显示
  thymeleaf:
    mode: LEGACYHTML5 #非完全严格检查,严格使用HTML5
    cache: false      #开发时关闭缓存以查看实时页面
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix:
      classpath: /templates
  servlet:
    multipart:
      max-file-size: 5MB
      enabled: false
  cache:
    type: caffeine