variable:
  introduce: '这是开发时候的配置 yml'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msg_collect?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    druid:
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录，500ms 以上为慢sql
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      useGlobalDataSourceStat: true                   # 合并多个DruidDataSource的监控数据
      # Druid WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: '*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*'
      # Druid StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1,192.168.43.145
        url-pattern: "/druid/*"
        reset-enable: true  #HTML页面上的“Reset All”功能
        login-username: admin
        login-password: admin

  jpa:
    show-sql: true    #开发时打开sql显示
  thymeleaf:
    cache: false      #开发时关闭缓存以查看实时页面


management:
  server:
    port: 8080
    address: 127.0.0.1
  endpoints:
    web:
      base-path: '/springManage'     # url 前缀
      exposure:
        include: '*'    # 开放所有 端点
    beans:
      cache:
        time-to-live:10s
  info:
    git:
      mode:
        full

# 构建信息
info:
  app:
    encoding:UTF-8
    java.source:1.8
    java.traget:1.8